#Datasource Properties
spring:
  datasource:
    url: jdbc:h2:mem:product
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    initialization-mode: always
  
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      show-sql: false
    
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
        trace: false
        
server:
  error:
    include-stacktrace: never
    
foreign:
  url: http://data.fixer.io/api/latest?access_key=
  access-key: 4aaa62511624273d73efb9611030c0cb
  symbols: USD,AUD,CAD,PLN,MXN

management:
  security:
    enabled: false