DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE product (
    id INT IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    description VARCHAR(250) NOT NULL,
    price NUMERIC (15,2) NOT NULL
);